"""First migration

Revision ID: 66b320700b3c
Revises: 
Create Date: 2019-07-26 18:00:53.204898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b320700b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('manufacturer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actor_actor_name'), 'actor', ['actor_name'], unique=True)
    op.create_index(op.f('ix_actor_email'), 'actor', ['email'], unique=True)
    op.create_table('adress',
    sa.Column('adress_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('zip_code', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['actor.id'], ),
    sa.PrimaryKeyConstraint('adress_id')
    )
    op.create_index(op.f('ix_adress_zip_code'), 'adress', ['zip_code'], unique=False)
    op.create_table('medicine',
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=140), nullable=True),
    sa.Column('GTIN', sa.String(length=14), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['actor.id'], ),
    sa.PrimaryKeyConstraint('medicine_id'),
    sa.UniqueConstraint('GTIN')
    )
    op.create_index(op.f('ix_medicine_medicine_name'), 'medicine', ['medicine_name'], unique=True)
    op.create_table('batch',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('exp_date', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.medicine_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_batch_batch_id'), 'batch', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_batch_id'), table_name='batch')
    op.drop_table('batch')
    op.drop_index(op.f('ix_medicine_medicine_name'), table_name='medicine')
    op.drop_table('medicine')
    op.drop_index(op.f('ix_adress_zip_code'), table_name='adress')
    op.drop_table('adress')
    op.drop_index(op.f('ix_actor_email'), table_name='actor')
    op.drop_index(op.f('ix_actor_actor_name'), table_name='actor')
    op.drop_table('actor')
    # ### end Alembic commands ###
