"""Updated the batch model

Revision ID: a5f331b6a97c
Revises: 66b320700b3c
Create Date: 2019-08-19 12:25:32.988946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f331b6a97c'
down_revision = '66b320700b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('parent_batch_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch', 'parent_batch_id')
    # ### end Alembic commands ###
